# Generated by Django 5.2.8 on 2025-12-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название языка')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year_created', models.IntegerField(verbose_name='Год создания')),
                ('main_application', models.CharField(max_length=200, verbose_name='Сфера применения')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Логотип')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный язык')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
                'ordering': ['name'],
            },
        ),
    ]
